Add object fusion tracks, fix sidebar names
NextDroid/potree pull request #276
Opened 2020-12-30 17:22 UTC by nmhaddadND

This PR adds support for Object Fusion Tracks and renames some items in our sidebar so that everything is correct.

2020-12-30 21:03 UTC, bcasselsND requested changes
`let` to `const`, wherever yo ucan.

2020-12-30 21:03 UTC, bcasselsND commented on demo/objectFusionTracksLoader.js
> +      });
You don't need `async` or `await` here. The progress thing gets called, and no one is waiting for the answer.

2020-12-30 21:03 UTC, bcasselsND commented on demo/objectFusionTracksLoader.js
> +        let centroidLocation;
Why is this `let` here? Why not just `const` below, where you get the value?

2020-12-30 21:23 UTC, nmhaddadND commented
I will make these changes, but just to be clear, this is more than likely a temporary fix for getting object fusion bounding boxes displayed in potree under the correct sidebar subtree. I copied and pasted almost all code from `trackLoader.js`, which @jallen-NextDroid is in the middle of redoing.

2020-12-31 15:55 UTC, bcasselsND approved these changes
A couple of nits.

2020-12-31 15:55 UTC, bcasselsND commented on demo/objectFusionTracksLoader.js
> +        stateTimes.push(state.timestamps()-animationEngine.tstart); // HACK -- 16.8 is a hack to get the tracked box timestamps to lineup with the rest of the animation
Is the comment still relevant? I see no 16.8 in the code.

2020-12-31 15:55 UTC, bcasselsND commented on demo/objectFusionTracksLoader.js
> +		for (let ii = 0, len = trackGeometries.bbox.length; ii < len; ii++) {
Indentation? [I hope you're not using tab characters.]

2020-12-31 15:59 UTC, merged